[theme]
base = "dark"
primaryColor = "#ff6b35"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0c0c0c"
textColor = "#f3f4f6"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = true
